#!/bin/bash

# Spostati nella directory dello script
# cd /home/midee/Documents/uni/scriptCalendario

BASE_DIR="/Users/nicola/Documents/GoogleCalendarUnife"

# Attiva il virtual environment
source "${BASE_DIR}/.venv/bin/activate"

# Specifica esplicitamente l'interprete Python dal venv
"${BASE_DIR}/.venv/bin/python3" "${BASE_DIR}/index.py"