#!/bin/bash

# Attiva il virtual environment
source .venv/bin/activate

# Specifica esplicitamente l'interprete Python dal venv
/home/midee/GoogleCalendarUnife/.venv/bin/python3.11 /home/midee/GoogleCalendarUnife/index.py > /home/midee/GoogleCalendarUnife/log 2>&1